use crate::control_plane::{PlanDefinition, StepDefinition, WorkflowOrchestrator};
use crate::executor::{
    ExecuteQueryRequest, GetSchemaRequest as ExecGetSchemaRequest,
    GetTableRequest as ExecGetTableRequest, QueryRuntimeAugmentor, QueryServiceImpl, QueryStatus,
    SchemaService, SchemaServiceImpl, ValidateQueryRequest,
};
use crate::interceptor::{get_event_bus, Event as DomainEvent};
use crate::runtime_context::QueryRuntimeContext;
use chrono::Utc;
use oam_proto::v1::agent::SchemaMode;
use std::collections::HashMap;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll};
use tokio::sync::Mutex;
use tokio_stream::Stream;
use tonic::{transport::Server, Request, Response, Status};

/// Generated proto types (imported from roam-proto)
/// These are generated by tonic-build from the proto files
use oam_proto::v1::agent::{
    agent_service_server::{AgentService as ProtoAgentService, AgentServiceServer},
    ConnectRequest, ConnectResponse, Event, EventStreamRequest,
};
use oam_proto::v1::control::{
    control_plane_service_server::{
        ControlPlaneService as ProtoControlPlaneService, ControlPlaneServiceServer,
    },
    CancelPlanRequest, CancelPlanResponse, ExecuteStepRequest, ExecuteStepResponse,
    GetPlanStatusRequest, GetPlanStatusResponse, LlmContextUpdate as ProtoLlmContextUpdate,
    PlanEvent, SchemaTableDelta as ProtoSchemaTableDelta, StepStatusRecord,
    StreamPlanEventsRequest, SubmitPlanRequest, SubmitPlanResponse,
};
use oam_proto::v1::query::{
    query_service_server::{QueryService as ProtoQueryService, QueryServiceServer},
    ExecuteQueryRequest as ProtoExecuteQueryRequest,
    ExecuteQueryResponse as ProtoExecuteQueryResponse,
    ValidateQueryRequest as ProtoValidateQueryRequest, ValidationResponse,
};
use oam_proto::v1::schema::{
    schema_service_server::{SchemaService as ProtoSchemaService, SchemaServiceServer},
    ColumnDef, FieldMappingDef, GetSchemaRequest, GetSchemaResponse, GetTableRequest,
    GetTableResponse, IndexDef, TableDef, TriggerDef, UserDefinedTypeDef,
};
use tokio_stream::wrappers::ReceiverStream;

/// Convert a [`crate::mirror::Table`] to its proto [`TableDef`] representation.
pub fn table_to_table_def(table: &crate::mirror::Table) -> TableDef {
    let columns = table
        .columns
        .iter()
        .map(|c| ColumnDef {
            name: c.name.clone(),
            data_type: c.sql_type.clone(),
            is_nullable: c.nullable,
            default_value: c.default_value.clone().unwrap_or_default(),
            is_primary_key: c.primary_key,
        })
        .collect();

    let mut indexes: Vec<IndexDef> = table
        .unique_indexes
        .iter()
        .map(|i| IndexDef {
            name: i.name.clone(),
            columns: i.columns.clone(),
            is_unique: true,
        })
        .collect();
    indexes.extend(table.indexes.iter().map(|i| IndexDef {
        name: i.name.clone(),
        columns: i.columns.clone(),
        is_unique: false,
    }));

    let triggers = table
        .triggers
        .iter()
        .map(|t| TriggerDef {
            name: t.name.clone(),
            timing: t.timing.clone(),
            event: t.event.clone(),
            body: t.body.clone(),
        })
        .collect();

    let field_mappings = table
        .field_mappings
        .iter()
        .map(|fm| FieldMappingDef {
            column_name: fm.physical_name.clone(),
            logical_name: fm.logical_name.clone(),
            convention: fm.orm_convention.clone(),
        })
        .collect();

    TableDef {
        name: table.name.clone(),
        columns,
        indexes,
        triggers,
        field_mappings,
    }
}

pub struct GrpcExecutor {
    query_service: Arc<Mutex<QueryServiceImpl>>,
    schema_service: Arc<Mutex<SchemaServiceImpl>>,
    sessions: Arc<SessionRegistry>,
    runtime_augmentor: Option<Arc<dyn QueryRuntimeAugmentor>>,
    access_enforcer: Option<Arc<dyn crate::access_policy::DataAccessEnforcer>>,
    workflow_orchestrator: Option<Arc<dyn WorkflowOrchestrator>>,
}

/// Basic implementation of AgentService for registration and event streaming
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RegisteredAgentSession {
    pub session_id: String,
    pub agent_id: String,
    pub version: String,
    pub schema_mode: SchemaMode,
}

impl RegisteredAgentSession {
    fn schema_mode_name(&self) -> &'static str {
        self.schema_mode.as_str_name()
    }
}

#[derive(Default)]
struct SessionRegistry {
    sessions: Mutex<HashMap<String, RegisteredAgentSession>>,
}

impl SessionRegistry {
    async fn insert(&self, session: RegisteredAgentSession) {
        self.sessions
            .lock()
            .await
            .insert(session.session_id.clone(), session);
    }

    async fn remove(&self, session_id: &str) {
        self.sessions.lock().await.remove(session_id);
    }

    async fn get(&self, session_id: &str) -> Option<RegisteredAgentSession> {
        self.sessions.lock().await.get(session_id).cloned()
    }
}

pub struct GrpcAgentServiceImpl {
    sessions: Arc<SessionRegistry>,
}

impl Default for GrpcAgentServiceImpl {
    fn default() -> Self {
        Self::new(Arc::new(SessionRegistry::default()))
    }
}

impl GrpcAgentServiceImpl {
    fn new(sessions: Arc<SessionRegistry>) -> Self {
        Self { sessions }
    }

    pub async fn registered_session(&self, session_id: &str) -> Option<RegisteredAgentSession> {
        self.sessions.get(session_id).await
    }

    pub async fn unregister_session(&self, session_id: &str) {
        self.sessions.remove(session_id).await;
    }
}

pub struct SessionEventStream {
    inner: ReceiverStream<Result<Event, Status>>,
    subscriber_id: Option<usize>,
}

impl Stream for SessionEventStream {
    type Item = Result<Event, Status>;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Pin::new(&mut self.inner).poll_next(cx)
    }
}

impl Drop for SessionEventStream {
    fn drop(&mut self) {
        if let Some(subscriber_id) = self.subscriber_id.take() {
            let _ = get_event_bus().unregister_subscriber(subscriber_id);
        }
    }
}

#[tonic::async_trait]
impl ProtoAgentService for GrpcAgentServiceImpl {
    async fn register(
        &self,
        request: Request<ConnectRequest>,
    ) -> Result<Response<ConnectResponse>, Status> {
        let req = request.into_inner();
        let schema_mode = SchemaMode::try_from(req.mode)
            .map_err(|_| Status::invalid_argument("unsupported schema mode"))?;
        let session = RegisteredAgentSession {
            session_id: uuid::Uuid::new_v4().to_string(),
            agent_id: req.agent_id,
            version: req.version,
            schema_mode,
        };

        self.sessions.insert(session.clone()).await;

        let _ = get_event_bus()
            .dispatch_generic(&DomainEvent::session_registered(session.session_id.clone()));

        Ok(Response::new(ConnectResponse {
            success: true,
            session_id: session.session_id,
        }))
    }

    type StreamEventsStream = SessionEventStream;

    async fn stream_events(
        &self,
        request: Request<EventStreamRequest>,
    ) -> Result<Response<Self::StreamEventsStream>, Status> {
        let session_id = request.into_inner().session_id;
        let (tx, rx) = tokio::sync::mpsc::channel(16);
        let requested_session_id = session_id.clone();
        let subscriber_id = get_event_bus()
            .register_subscriber(Box::new(move |event: &DomainEvent| {
                let metadata = event.metadata();
                if metadata.get("session_id") != Some(&requested_session_id) {
                    return;
                }

                if let Ok(payload) = serde_json::to_vec(event) {
                    let _ = tx.try_send(Ok(Event {
                        r#type: event.event_type().to_string(),
                        payload,
                        typed_payload: None,
                    }));
                }
            }))
            .map_err(Status::internal)?;

        Ok(Response::new(SessionEventStream {
            inner: ReceiverStream::new(rx),
            subscriber_id: Some(subscriber_id),
        }))
    }
}

impl GrpcExecutor {
    pub fn new(db_path: &str) -> Result<Self, String> {
        let mut query_service = QueryServiceImpl::new();
        let mut schema_service = SchemaServiceImpl::new();

        query_service.set_db_path(db_path)?;
        schema_service.set_db_path(db_path)?;

        Ok(Self {
            query_service: Arc::new(Mutex::new(query_service)),
            schema_service: Arc::new(Mutex::new(schema_service)),
            sessions: Arc::new(SessionRegistry::default()),
            runtime_augmentor: None,
            access_enforcer: None,
            workflow_orchestrator: None,
        })
    }

    pub fn with_runtime_augmentor(mut self, augmentor: Arc<dyn QueryRuntimeAugmentor>) -> Self {
        self.runtime_augmentor = Some(augmentor);
        self
    }

    pub fn with_access_enforcer(
        mut self,
        enforcer: Arc<dyn crate::access_policy::DataAccessEnforcer>,
    ) -> Self {
        self.access_enforcer = Some(enforcer);
        self
    }

    pub fn with_workflow_orchestrator(mut self, orch: Arc<dyn WorkflowOrchestrator>) -> Self {
        self.workflow_orchestrator = Some(orch);
        self
    }

    pub async fn start_server(
        self,
        addr: &str,
    ) -> Result<tokio::task::JoinHandle<()>, Box<dyn std::error::Error>> {
        let addr_parsed = addr.parse()?;

        if let Some(augmentor) = self.runtime_augmentor.clone() {
            let mut query_service = self.query_service.lock().await;
            query_service.set_runtime_augmentor(augmentor);
        }

        if let Some(enforcer) = self.access_enforcer.clone() {
            let mut query_service = self.query_service.lock().await;
            query_service.set_access_enforcer(enforcer);
        }

        let query_svc = GrpcQueryServiceImpl {
            inner: self.query_service.clone(),
            sessions: self.sessions.clone(),
        };
        let schema_svc = GrpcSchemaServiceImpl {
            inner: self.schema_service.clone(),
        };

        let agent_svc = GrpcAgentServiceImpl::new(self.sessions.clone());

        let maybe_cp_svc = self.workflow_orchestrator.map(|orch| {
            ControlPlaneServiceServer::new(GrpcControlPlaneServiceImpl { orchestrator: orch })
        });

        let handle = tokio::spawn(async move {
            let builder = Server::builder()
                .add_service(QueryServiceServer::new(query_svc))
                .add_service(SchemaServiceServer::new(schema_svc))
                .add_service(AgentServiceServer::new(agent_svc));

            if let Some(cp_svc) = maybe_cp_svc {
                let _ = builder.add_service(cp_svc).serve(addr_parsed).await;
            } else {
                let _ = builder.serve(addr_parsed).await;
            }
        });

        Ok(handle)
    }
}

struct GrpcQueryServiceImpl {
    inner: Arc<Mutex<QueryServiceImpl>>,
    sessions: Arc<SessionRegistry>,
}

impl GrpcQueryServiceImpl {
    /// Enriches a `QueryRuntimeContext` with the registered agent metadata for the
    /// associated session, if one is present. This is the single authoritative place
    /// where session state is promoted into the request context.
    async fn enrich_context_from_session(
        &self,
        context: QueryRuntimeContext,
    ) -> QueryRuntimeContext {
        let Some(session_id) = context.session_id.clone() else {
            return context;
        };
        let Some(session) = self.sessions.get(&session_id).await else {
            return context;
        };
        context.with_registered_agent(
            &session.agent_id,
            &session.version,
            session.schema_mode_name(),
        )
    }
}

#[tonic::async_trait]
impl ProtoQueryService for GrpcQueryServiceImpl {
    async fn execute_query(
        &self,
        request: Request<ProtoExecuteQueryRequest>,
    ) -> Result<Response<ProtoExecuteQueryResponse>, Status> {
        let runtime_context = self
            .enrich_context_from_session(QueryRuntimeContext::from_metadata(request.metadata()))
            .await;
        let req = request.into_inner();

        let exec_req = ExecuteQueryRequest {
            db_identifier: req.db_identifier,
            query: req.query,
            parameters: Default::default(),
            limit: req.limit,
            timeout_seconds: req.timeout_seconds,
        };

        let validate_req = ValidateQueryRequest {
            db_identifier: exec_req.db_identifier.clone(),
            query: exec_req.query.clone(),
            parameters: Default::default(),
        };

        let service = self.inner.lock().await;

        let validation = service
            .validate_query_with_runtime_context(validate_req, runtime_context.clone())
            .await
            .map_err(Status::internal)?;

        if !validation.valid {
            let timestamp = Utc::now().to_rfc3339();
            // Merge runtime context metadata with any augmentation metadata returned by
            // validation (e.g. resolved_runtime_augmentation_id from a prompt hook).
            let mut event_metadata = runtime_context.event_metadata();
            for (k, v) in validation.event_metadata {
                event_metadata.entry(k).or_insert(v);
            }
            let event = DomainEvent::query_validation_failed(
                exec_req.db_identifier.clone(),
                exec_req.query.clone(),
                validation.error_message.clone(),
                timestamp.clone(),
                event_metadata,
            );
            if let Err(e) = get_event_bus().dispatch_generic(&event) {
                eprintln!("Event dispatch failed for query_validation_failed: {}", e);
            }

            return Ok(Response::new(ProtoExecuteQueryResponse {
                status: QueryStatus::ValidationError as i32,
                row_count: 0,
                execution_ms: 0,
                error_message: validation.error_message,
                timestamp,
            }));
        }

        match service
            .execute_query_with_runtime_context(exec_req, runtime_context)
            .await
        {
            Ok(resp) => Ok(Response::new(ProtoExecuteQueryResponse {
                status: resp.status,
                row_count: resp.row_count,
                execution_ms: resp.execution_ms,
                error_message: resp.error_message,
                timestamp: resp.timestamp,
            })),
            Err(e) => Err(Status::internal(e)),
        }
    }

    async fn validate_query(
        &self,
        request: Request<ProtoValidateQueryRequest>,
    ) -> Result<Response<ValidationResponse>, Status> {
        let runtime_context = self
            .enrich_context_from_session(QueryRuntimeContext::from_metadata(request.metadata()))
            .await;
        let req = request.into_inner();

        let exec_req = ValidateQueryRequest {
            db_identifier: req.db_identifier,
            query: req.query,
            parameters: Default::default(),
        };

        let service = self.inner.lock().await;
        match service
            .validate_query_with_runtime_context(exec_req, runtime_context)
            .await
        {
            Ok(resp) => Ok(Response::new(ValidationResponse {
                valid: resp.valid,
                error_message: resp.error_message,
            })),
            Err(e) => Err(Status::internal(e)),
        }
    }
}

struct GrpcSchemaServiceImpl {
    inner: Arc<Mutex<SchemaServiceImpl>>,
}

#[tonic::async_trait]
impl ProtoSchemaService for GrpcSchemaServiceImpl {
    async fn get_schema(
        &self,
        request: Request<GetSchemaRequest>,
    ) -> Result<Response<GetSchemaResponse>, Status> {
        let req = request.into_inner();

        let exec_req = ExecGetSchemaRequest {
            db_identifier: req.db_identifier,
        };

        let service = self.inner.lock().await;
        match service.get_schema(exec_req).await {
            Ok(schema_resp) => {
                let tables = schema_resp.tables.iter().map(table_to_table_def).collect();
                let user_defined_types = schema_resp
                    .user_defined_types
                    .iter()
                    .map(|u| UserDefinedTypeDef {
                        name: u.name.clone(),
                        base_type: u.base_type.clone(),
                        variants: vec![],
                    })
                    .collect();
                Ok(Response::new(GetSchemaResponse {
                    schema_id: schema_resp.schema_id,
                    database_type: schema_resp.database_type,
                    generated_at: schema_resp.generated_at,
                    tables,
                    user_defined_types,
                }))
            }
            Err(e) => Err(Status::internal(e)),
        }
    }

    async fn get_table(
        &self,
        request: Request<GetTableRequest>,
    ) -> Result<Response<GetTableResponse>, Status> {
        let req = request.into_inner();

        let exec_req = ExecGetTableRequest {
            db_identifier: req.db_identifier,
            table_name: req.table_name,
        };

        let service = self.inner.lock().await;
        match service.get_table(exec_req).await {
            Ok(table_resp) => Ok(Response::new(GetTableResponse {
                generated_at: table_resp.generated_at,
                table: table_resp.table.as_ref().map(table_to_table_def),
            })),
            Err(e) => Err(Status::internal(e)),
        }
    }

    // Add RegisterSchema RPC here when CODE_FIRST mode support is needed.
    // Validate agent SchemaMode == CODE_FIRST or HYBRID before accepting registration;
    // DATA_FIRST agents must receive PermissionDenied.
}

// ── ControlPlane gRPC service ─────────────────────────────────────────────────

struct GrpcControlPlaneServiceImpl {
    orchestrator: Arc<dyn WorkflowOrchestrator>,
}

/// Streaming response type for `stream_plan_events`.
pub struct PlanEventStream {
    inner: ReceiverStream<Result<PlanEvent, Status>>,
    subscriber_id: Option<usize>,
}

impl Stream for PlanEventStream {
    type Item = Result<PlanEvent, Status>;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Pin::new(&mut self.inner).poll_next(cx)
    }
}

impl Drop for PlanEventStream {
    fn drop(&mut self) {
        if let Some(subscriber_id) = self.subscriber_id.take() {
            let _ = get_event_bus().unregister_subscriber(subscriber_id);
        }
    }
}

/// Map proto `PlanStepDef` intent string to internal `ToolIntent`.
fn parse_proto_intent(s: &str) -> crate::policy_engine::ToolIntent {
    use crate::policy_engine::ToolIntent;
    match s.trim().to_ascii_lowercase().as_str() {
        "write_insert" | "writeinsert" | "insert" => ToolIntent::WriteInsert,
        "write_update" | "writeupdate" | "update" => ToolIntent::WriteUpdate,
        "write_delete" | "writedelete" | "delete" => ToolIntent::WriteDelete,
        "admin" => ToolIntent::Admin,
        _ => ToolIntent::ReadSelect,
    }
}

/// Map a domain [`crate::control_plane::StepResult`] to its proto [`StepStatusRecord`].
fn step_result_to_proto(r: &crate::control_plane::StepResult) -> StepStatusRecord {
    StepStatusRecord {
        step_id: r.step_id.clone(),
        name: r.step_id.clone(), // fallback until StepResult carries a display name
        status: r.status.as_str().to_string(),
        row_count: r.row_count,
        result_json: r.output_json.clone(),
        schema_delta_json: r.schema_delta_json.clone(),
        executed_at: r.executed_at.clone(),
    }
}

/// Map a domain [`crate::control_plane::LlmContextUpdate`] to its proto counterpart.
fn llm_context_update_to_proto(u: crate::control_plane::LlmContextUpdate) -> ProtoLlmContextUpdate {
    ProtoLlmContextUpdate {
        plan_id: u.plan_id,
        step_id: u.step_id,
        tool_output_json: u.tool_output_json,
        schema_additions: u
            .schema_additions
            .into_iter()
            .map(|d| ProtoSchemaTableDelta {
                table_name: d.table_name,
                operation: format!("{:?}", d.operation).to_uppercase(),
                table_def_json: d.table_def_json,
            })
            .collect(),
        augmentation_hints: u.augmentation_hints,
    }
}

#[tonic::async_trait]
impl ProtoControlPlaneService for GrpcControlPlaneServiceImpl {
    // ── SubmitPlan ────────────────────────────────────────────────────────────
    async fn submit_plan(
        &self,
        request: Request<SubmitPlanRequest>,
    ) -> Result<Response<SubmitPlanResponse>, Status> {
        let req = request.into_inner();
        let session_id = req.session_id.clone();
        let def = PlanDefinition {
            name: req.name,
            description: req.description,
            steps: req
                .steps
                .into_iter()
                .map(|s| StepDefinition {
                    id: s.id,
                    name: s.name,
                    tool_name: s.tool_name,
                    tool_intent: parse_proto_intent(&s.intent),
                    query_template: s.query_template,
                    depends_on: s.depends_on,
                    schema_table_hints: s.schema_table_hints,
                })
                .collect(),
        };
        match self.orchestrator.create_plan(&session_id, def).await {
            Ok(record) => Ok(Response::new(SubmitPlanResponse {
                success: true,
                plan_id: record.plan_id,
                error_message: String::new(),
            })),
            Err(e) => Ok(Response::new(SubmitPlanResponse {
                success: false,
                plan_id: String::new(),
                error_message: e,
            })),
        }
    }

    // ── GetPlanStatus ─────────────────────────────────────────────────────────
    async fn get_plan_status(
        &self,
        request: Request<GetPlanStatusRequest>,
    ) -> Result<Response<GetPlanStatusResponse>, Status> {
        let plan_id = request.into_inner().plan_id;
        match self.orchestrator.get_plan(&plan_id).await {
            Ok(Some(record)) => {
                let steps = record.steps.iter().map(step_result_to_proto).collect();
                Ok(Response::new(GetPlanStatusResponse {
                    plan_id: record.plan_id,
                    status: record.status.as_str().to_string(),
                    steps,
                    error_message: String::new(),
                }))
            }
            Ok(None) => Err(Status::not_found(format!("plan '{}' not found", plan_id))),
            Err(e) => Err(Status::internal(e)),
        }
    }

    // ── ExecuteStep ───────────────────────────────────────────────────────────
    async fn execute_step(
        &self,
        request: Request<ExecuteStepRequest>,
    ) -> Result<Response<ExecuteStepResponse>, Status> {
        let mut ctx = QueryRuntimeContext::from_metadata(request.metadata());
        let req = request.into_inner();
        ctx.plan_id = Some(req.plan_id.clone());

        match self
            .orchestrator
            .execute_step(&req.plan_id, &req.step_id, &ctx)
            .await
        {
            Ok((step_result, ctx_update)) => Ok(Response::new(ExecuteStepResponse {
                success: true,
                step_result: Some(step_result_to_proto(&step_result)),
                llm_context_update: Some(llm_context_update_to_proto(ctx_update)),
                error_message: String::new(),
            })),
            Err(e) => Ok(Response::new(ExecuteStepResponse {
                success: false,
                step_result: None,
                llm_context_update: None,
                error_message: e,
            })),
        }
    }

    // ── CancelPlan ────────────────────────────────────────────────────────────
    async fn cancel_plan(
        &self,
        request: Request<CancelPlanRequest>,
    ) -> Result<Response<CancelPlanResponse>, Status> {
        let plan_id = request.into_inner().plan_id;
        match self.orchestrator.cancel_plan(&plan_id).await {
            Ok(()) => Ok(Response::new(CancelPlanResponse {
                success: true,
                error_message: String::new(),
            })),
            Err(e) => Ok(Response::new(CancelPlanResponse {
                success: false,
                error_message: e,
            })),
        }
    }

    // ── StreamPlanEvents ──────────────────────────────────────────────────────
    type StreamPlanEventsStream = PlanEventStream;

    async fn stream_plan_events(
        &self,
        request: Request<StreamPlanEventsRequest>,
    ) -> Result<Response<Self::StreamPlanEventsStream>, Status> {
        let requested_plan_id = request.into_inner().plan_id;
        let (tx, rx) = tokio::sync::mpsc::channel(32);
        let subscriber_id = get_event_bus()
            .register_subscriber(Box::new(move |event: &DomainEvent| {
                let metadata = event.metadata();
                if metadata.get("plan_id").map(String::as_str) != Some(requested_plan_id.as_str()) {
                    return;
                }
                let event_type = event.event_type().to_string();
                let payload_json = serde_json::to_string(event).unwrap_or_default();
                let timestamp = Utc::now().to_rfc3339();
                let _ = tx.try_send(Ok(PlanEvent {
                    plan_id: requested_plan_id.clone(),
                    event_type,
                    payload_json,
                    timestamp,
                }));
            }))
            .map_err(Status::internal)?;

        Ok(Response::new(PlanEventStream {
            inner: ReceiverStream::new(rx),
            subscriber_id: Some(subscriber_id),
        }))
    }
}
